### ISSUE TITLE
Issues with barcode scanner & Question about NFC

### ISSUE THREAD

**Issue by NOaMTL** [Mahmoudmv91/pax_player#2]
Hello,

I successfuly installed the package in a flutter new project, and used your demo code, but I have issue when i open the barcode-scanner :

Device is a PAX A920

E/art     ( 4461): No implementation found for int pax.util.OsPaxApi.ScanOpenHW() (tried Java_pax_util_OsPaxApi_ScanOpenHW and Java_pax_util_OsPaxApi_ScanOpenHW__)
com.pax.api.scanner.hw.ScannerHwException: Not Support for this device

Also do you know how to implement the NFC car reader of the 920 ? nfc_manager does not work with the A920 (I guess A920 does not use the hardware NFC)

Thank you

**Comment by Mahmoudmv91** [comment]
Hello,

Thank you for your feedback! Based on the error message, it seems like the PAX A920 device does not support the specific hardware scanner you are trying to access (ScanOpenHW). Unfortunately, the A920 doesn't have full compatibility with all scanning hardware features.

As for the NFC question, you're right. The PAX A920 does not come with NFC hardware, which is why packages like nfc_manager won’t work with this device.

Please let me know if you need any further assistance!

Best regards,
